'use strict';
let data;
let gwSelection, monthSelection;
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = (n, digits = 0) => n == null ? '—' : Number(n).toLocaleString(undefined, {maximumFractionDigits:digits});
const movement = n => `<span class="movement ${n > 0 ? 'up' : n < 0 ? 'down' : 'neutral'}" aria-label="${n == null ? 'No previous rank' : n > 0 ? `Up ${n} places` : n < 0 ? `Down ${-n} places` : 'No change'}">${n > 0 ? '↑ '+n : n < 0 ? '↓ '+Math.abs(n) : '—'}</span>`;
const medal = rank => `<span class="rank-badge r${rank}" ${rank <= 3 ? `aria-label="${['','Gold','Silver','Bronze'][rank]}, position ${rank}"` : ''}>${rank}</span>`;
const person = (m, avatar = false) => `<div class="manager-cell">${avatar ? `<span class="avatar" aria-hidden="true">${esc(m.team.split(' ').map(x=>x[0]).slice(0,2).join(''))}</span>` : ''}<button class="manager-btn" data-manager="${m.id}"><strong>${esc(m.team)}</strong><small>${esc(m.name)}</small></button></div>`;
const empty = message => `<div class="empty">${message}</div>`;
function table(headers, rows, cls = '') { return `<div class="table-scroll ${cls}" tabindex="0" aria-label="Scrollable statistics table"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`; }
const cell = (x, cls = '') => `<td class="${cls}">${x}</td>`;
const row = cells => `<tr>${cells.join('')}</tr>`;
function heading(title, description, control = '') { return `<div class="page-heading"><div><p class="eyebrow">${esc(data.season)} SEASON / LEAGUE ${data.league_id}</p><h1>${esc(title)}</h1><p class="subtext">${description}</p></div>${control || `<span class="pill"><i></i>${data.latest_completed ? `GW ${data.latest_completed} complete` : 'Season warming up'}</span>`}</div>`; }
function spark(history) { if(!history.length) return ''; const values=history.map(r=>r.net); const lo=Math.min(...values)-5, hi=Math.max(...values)+5; return `<svg class="spark" viewBox="0 0 230 58" role="img" aria-label="Recent scores: ${values.join(', ')}"><line x1="0" x2="230" y1="54" y2="54"/><polyline points="${values.map((v,i)=>`${values.length===1?115:5+i*220/(values.length-1)},${50-(v-lo)/(hi-lo)*45}`).join(' ')}"/></svg>`; }
function award(label, managers, value, detail='') { if(!managers.length) return ''; return `<article class="stat-card"><p class="label">${label}</p><p class="stat">${value}</p>${managers.map(m=>person(m)).join('')}<p class="detail">${detail}</p></article>`; }
function best(items, key, low = false) { const available=items.filter(m=>m[key]!=null); if(!available.length)return []; const target=(low?Math.min:Math.max)(...available.map(m=>m[key])); return available.filter(m=>m[key]===target); }
const sortedManagers = () => [...data.managers].sort((a,b)=>a.rank-b.rank);
function projectionTable(compact=false) {
 const ms = data.managers.filter(m=>m.projected_total!=null).sort((a,b)=>a.projected_position-b.projected_position);
 if(!ms.length)return empty('Projections will appear after the first completed Gameweek.');
 const max=Math.max(1,...ms.map(m=>m.projected_total));
 return table(compact?['Projected','Manager','Current rank','Projected total','Change']:['Finish','Manager','Current points','Current rank','Last 5 avg','Projected total','Change'],ms.map(m=>row([
 cell(medal(m.projected_position),'rank-cell'),cell(person(m)),...(!compact?[cell(num(m.total),'numeric')]:[]),cell('#'+m.rank,'numeric'),...(!compact?[cell(num(m.recent_average,1),'numeric')]:[]),
 cell(`<div class="projection-bar"><span>${num(m.projected_total)}</span><div class="power-track"><i style="width:${Math.max(0,m.projected_total)/max*100}%"></i></div></div>`),cell(movement(m.rank-m.projected_position))])));
}
function home() {
 const ms=sortedManagers(), last=data.gameweeks.at(-1), winner=last?best(last.rows,'net'):[], form=best(ms,'recent_average'), high=best(ms,'best'), up=best(ms.filter(m=>m.movement>0),'movement'), down=best(ms.filter(m=>m.movement<0),'movement',true), power=best(ms,'power')[0];
 return heading(data.name, `${ms.length} managers. One league. Everything to play for.`)+
 `<div class="layout"><section class="panel"><div class="panel-heading"><h2>League standings</h2><span class="subtext">${data.in_progress?'Provisional':'Overall'}</span></div>${ms.length?table(['Pos','Manager / team','Total','Last GW','↕'],ms.map(m=>row([cell(medal(m.rank),'rank-cell'),cell(person(m,true)),cell(num(m.total),'numeric total'),cell(num(m.latest_score),'numeric'),cell(movement(m.movement),'movement-cell')])),'standings'):empty('No managers have scored yet.')}<p class="table-note">Last GW = points after hits. Select a manager to see their stats.</p></section>
 <aside class="side-stack">${winner.length?`<section class="panel spotlight"><span class="award-icon" aria-hidden="true">🏆</span><p class="eyebrow">GAMEWEEK ${last.id} / WINNER${winner.length>1?'S':''}</p><h2>${winner.map(m=>person(m)).join('')}</h2><div class="hero-score">${num(winner[0].net)}<span>net points</span></div><p class="subtext muted">This week's bragging rights.</p></section>`:''}
 ${power?`<section class="panel side-card"><p class="eyebrow">THE FORM GUIDE</p><h3>Setting the pace</h3><div class="power-mini">${person(power)}<span class="power-number">${power.power}</span></div><div class="power-track"><i style="width:${power.power}%"></i></div><p>Power Rating <span class="tooltip" title="Power Rating combines recent Gameweek performance, recent form, season form and rank momentum.">ⓘ</span> · ${power.form}</p>${spark(power.recent)}</section>`:''}
 <section class="panel side-card"><p class="eyebrow">THE LONG GAME</p><h3>${data.completed_count} down. ${data.total_gameweeks-data.completed_count} to go.</h3><p>A few green arrows can change everything.</p><div class="power-track"><i style="width:${data.completed_count/data.total_gameweeks*100}%"></i></div></section></aside></div>
 <section class="section"><div class="section-title"><h2>Around the league</h2><span class="subtext">The talking points</span></div><div class="cards">
 ${award('👑 Current league leader',ms.filter(m=>m.rank===1),num(ms[0]?.total)+' pts')}
 ${award('⚡ Highest Gameweek score',high,num(high[0]?.best)+' pts','Season record · after hits')}
 ${award('🔥 Best recent form',form,num(form[0]?.recent_average,1)+' avg','Last 5 available Gameweeks')}
 ${award('📈 Biggest green arrow',up,up.length?'↑ '+up[0].movement+' places':'')}
 ${award('📉 Biggest red arrow',down,down.length?'↓ '+Math.abs(down[0].movement)+' places':'')}
 ${award('🪑 Most bench points',best(ms,'bench'),num(best(ms,'bench')[0]?.bench)+' pts','Completed Gameweeks')}
 </div></section><section class="section panel"><div class="panel-heading"><h2>Projected final standings</h2><a class="text-link" href="#predictions">The full picture ↗</a></div>${projectionTable(true)}<p class="table-note">Simple statistical projection based on current and recent form — not a guarantee.</p></section>`;
}
function gameweeks() {
 const weeks=data.gameweeks; if(!weeks.length)return heading('Gameweek centre','The weekly highs, lows and captain calls.')+empty('The first completed Gameweek will appear here once FPL has checked the final scores.');
 const gw=weeks.find(w=>w.id===Number(gwSelection))||weeks.at(-1); gwSelection=gw.id;
 const controls=`<div class="filters"><label class="sr-label" for="gw-select">Gameweek</label><select id="gw-select">${[...weeks].reverse().map(w=>`<option value="${w.id}" ${w.id===gw.id?'selected':''}>Gameweek ${w.id}</option>`).join('')}</select></div>`;
 const awards=[['🏆 Manager of the Week','net',false,' pts'],['💀 Lowest score','net',true,' pts'],['🎯 Best captain return','captain_points',false,' pts'],['🪑 Most bench points','bench',false,' pts'],['📈 Biggest rank gain','movement',false,' places'],['📉 Biggest rank drop','movement',true,' places']];
 return heading('Gameweek '+gw.id,`Deadline: ${new Date(gw.deadline).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})} · Final scores`,controls)+
 `<div class="cards">${awards.map(([label,key,low,suffix])=>{const eligible=gw.rows.filter(r=>key!=='movement'||(low?r[key]<0:r[key]>0));const winners=best(eligible,key,low);return award(label,winners,num(key==='movement'?Math.abs(winners[0]?.[key]):winners[0]?.[key])+suffix);}).join('')}</div><section class="section panel"><div class="panel-heading"><h2>The Gameweek table</h2><span class="subtext">After transfer hits</span></div>`+
 table(['GW rank','Manager','Net points','Captain','Captain pts','Bench','Transfers','Hit cost','Total after GW','League rank / move'],gw.rows.map(r=>row([cell(medal(r.gw_rank)),cell(person(r)+(r.chip?`<span class="chip">${esc(chipName(r.chip))}</span>`:'')),cell(`<strong>${r.net}</strong><small class="muted"> (${r.gross} − ${r.hits})</small>`),cell(esc(r.captain||'—')),cell(num(r.captain_points)),cell(r.bench),cell(r.transfers),cell(r.hits?`−${r.hits}`:'0'),cell(num(r.total)),cell('#'+r.league_rank+' '+movement(r.movement))])))+
 `<p class="table-note">Captain points include the final multiplier, including vice-captain fallback. Bench is FPL's points left on the bench; Bench Boost points are already in the score. Tied weekly winners share the award.</p></section>`;
}
function chipName(chip){return {wildcard:'Wildcard',freehit:'Free Hit','3xc':'Triple Captain',bboost:'Bench Boost'}[chip]||chip;}
function monthly(){
 if(!data.months.length)return heading('Month by month','A fresh race, every month.')+empty('Monthly standings appear after the first completed Gameweek.');
 const month=data.months.find(m=>m.id===monthSelection)||data.months.at(-1);monthSelection=month.id;
 const control=`<div class="filters"><label for="month-select">Month</label><select id="month-select">${[...data.months].reverse().map(m=>`<option value="${m.id}" ${month.id===m.id?'selected':''}>${esc(m.label)}</option>`).join('')}</select></div>`;
 const winners=best(month.rows,'points');
 return heading('Month by month',`Gameweeks ${month.gameweeks.join(', ')} · grouped by deadline month (UK time)`,control)+`<div class="cards">${award('🏆 Manager of the Month',winners,num(winners[0]?.points)+' pts',month.label)}</div><section class="section panel"><div class="panel-heading"><h2>${esc(month.label)}</h2><span class="subtext">${month.gameweeks.length} completed GWs</span></div>`+table(['Position','Manager','Points','Average','Best GW','Worst GW','Season rank change'],month.rows.map(m=>row([cell(medal(m.rank)),cell(person(m)),cell(num(m.points),'total'),cell(num(m.average,1)),cell(m.best),cell(m.worst),cell(movement(m.movement))])))+`<p class="table-note">Monthly scores include transfer hits in each included GW. Rank change compares the season table before and after the month; the first month has no prior rank. An ongoing month only includes completed Gameweeks.</p></section>`;
}
function season(){
 const ms=sortedManagers();
 const records=[['🏆 Most GW wins','wins',' wins'],['⚡ Highest single GW','best',' pts'],['🪑 Most bench points','bench',' pts'],['↔ Most transfer hits','hits',' pts spent'],['🔥 Best average score','average',' pts / GW'],['🚀 Biggest weekly rise','biggest_rise',' places']];
 return heading('The season so far','Every point, every captain call, every green arrow.')+`<div class="cards">${records.map(([label,key,suffix])=>{const winners=best(ms,key);return award(label,winners,num(winners[0]?.[key],1)+suffix);}).join('')}</div><section class="section panel"><div class="panel-heading"><h2>Season statistics</h2><span class="subtext">Scroll for all stats →</span></div>`+table(['Rank','Manager','Total','Avg GW','Best','Worst','Bench','Captain pts','Hit cost','Transfers','Highest pos','Lowest pos','GW wins','Squad value'],ms.map(m=>row([cell('#'+m.rank),cell(person(m)),cell(num(m.total),'total'),cell(num(m.average,1)),cell(num(m.best)),cell(num(m.worst)),cell(num(m.bench)),cell(captainTotal(m)),cell(num(m.hits)),cell(num(m.transfers)),cell(num(m.highest_position)),cell(num(m.lowest_position)),cell(num(m.wins)),cell(m.value?'£'+num(m.value,1)+'m':'—')])),'wide-table')+`<p class="table-note">Statistics use completed Gameweeks. Squad value is the latest public deadline value, excluding money in the bank. Historical positions are reconstructed among today's members, with fewer non-chip transfers breaking points ties.</p></section><section class="section"><div class="section-title"><h2>Power Rating <span class="tooltip" title="Power Rating combines recent Gameweek performance, recent form, season form and rank momentum.">ⓘ</span></h2><span class="subtext">Relative to our league</span></div><div class="power-cards">${[...ms].sort((a,b)=>(b.power??-1)-(a.power??-1)).map(m=>`<article class="panel power-card">${person(m)}<div class="power-mini"><span class="subtext">${esc(m.form)}</span><span class="power-number">${num(m.power)}</span></div><div class="power-track"><i style="width:${m.power||0}%"></i></div>${spark(m.recent)}<p class="subtext">GW ${num(m.latest_score)} · Last 5 avg ${num(m.recent_average,1)} · #${m.rank}</p></article>`).join('')}</div></section><details class="section panel"><summary>How Power Rating works</summary><p>40% latest completed GW score + 30% last five available GW average + 20% season average + 10% rank movement across the last five completed GWs. Each component is scaled from 0 to 100 within this league; everyone gets 50 for a component when all values match. The weighted result is rounded to a whole number. This is a transparent form score, not AI or a win probability.</p></details>`;
}
function captainTotal(m){return m.captain_points==null?'—':num(m.captain_points)+(m.captain_coverage<m.completed_count?` <small class="muted">(${m.captain_coverage}/${m.completed_count} GWs)</small>`:'');}
function predictions(){return heading('The run-in, projected','A little form. A little arithmetic. Plenty still to play for.')+`<section class="panel formula"><div><p class="eyebrow">EXPECTED POINTS PER GAMEWEEK</p><div class="formula-math">65% recent form + 35% season average</div></div><p><strong>${data.total_gameweeks-data.completed_count} Gameweeks remaining.</strong> Recent form uses the last five available completed GWs. Projected points add expected future scoring to the total after the last completed GW.</p></section><section class="section panel"><div class="panel-heading"><h2>Projected final table</h2><span class="subtext">${data.total_gameweeks} Gameweeks</span></div>${projectionTable()}<p class="table-note">Simple statistical projection based on current and recent form — not a guarantee.</p></section><details class="section panel" open><summary>Show the working</summary><p>Expected future GW score = (last 5 average × 0.65) + (season average × 0.35). Projected total = completed-GW total + (expected future score × remaining GWs). Scores include transfer hits. In-progress Gameweeks are excluded from averages and counted among the remaining GWs. Current points and current rank remain the official standings. Equal rounded projections share a finishing position. Injuries, fixtures and future chips are not modelled.</p></details>`;}
function showProfile(id){const m=data.managers.find(m=>m.id===Number(id));if(!m)return;const max=Math.max(1,...m.recent.map(r=>r.net));
 $('#profile-content').innerHTML=`<p class="eyebrow">MANAGER PROFILE</p><h2 id="profile-title">${esc(m.team)}</h2><p class="muted">${esc(m.name)}</p><div class="profile-top"><div><p class="eyebrow">LEAGUE POSITION</p><h2>#${m.rank} <span class="muted">/ ${data.managers.length}</span></h2></div><div><p class="eyebrow">TOTAL POINTS</p><h2>${num(m.total)}</h2></div><div><p class="eyebrow">POWER RATING</p><span class="power-number">${num(m.power)}</span></div></div><h3>Last ${m.recent.length} Gameweeks <small class="muted">· after hits</small></h3><div class="bar-chart">${m.recent.map(r=>`<div class="bar-column"><b>${r.net}</b><i style="height:${Math.max(3,r.net/max*85)}px"></i><span>GW ${r.gw}</span></div>`).join('')}</div><div class="profile-stats">${[['Best GW',num(m.best)],['Worst GW',num(m.worst)],['Average',num(m.average,1)],['GW wins',num(m.wins)],['Captain points',captainTotal(m)],['Bench points',num(m.bench)],['Transfers',num(m.transfers)],['Hit cost',num(m.hits)+' pts'],['Projected finish',m.projected_position?'#'+m.projected_position:'—']].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div>`;
 $('#profile').showModal();}
function render(){if(!data)return;const route=location.hash.slice(1)||'home';const pages={home,gameweeks,monthly,season,predictions};const active=pages[route]?route:'home';document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===active);if(a.dataset.nav===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 let notice=data.in_progress?`<div class="notice">Gameweek ${data.current_gw} is in progress or awaiting final checks. Current standings may be provisional; other stats stop at GW ${data.latest_completed||'—'}.</div>`:'';
 if(Date.now()-new Date(data.updated_at).getTime()>18*3600000)notice+='<div class="notice">The latest refresh is delayed. Showing the last successful snapshot.</div>';
 if(data.warnings.length)notice+='<div class="notice">Some captain details could not be refreshed. Available previous details are retained; missing values show as —.</div>';
 $('#content').innerHTML=`<div class="fade">${notice}${pages[active]()}</div>`;
 document.title=`${active==='home'?data.name:active[0].toUpperCase()+active.slice(1)} · Touchline`;
}
document.addEventListener('click',event=>{const button=event.target.closest('[data-manager]');if(button)showProfile(button.dataset.manager);});
document.addEventListener('change',event=>{if(event.target.id==='gw-select'){gwSelection=event.target.value;render();$('#gw-select')?.focus();}if(event.target.id==='month-select'){monthSelection=event.target.value;render();$('#month-select')?.focus();}});
$('#profile .close').addEventListener('click',()=>$('#profile').close());
$('#profile').addEventListener('click',e=>{if(e.target===$('#profile')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
async function load(){try{const response=await fetch('./data/league.json',{cache:'no-cache'});if(!response.ok)throw new Error('Snapshot unavailable');data=await response.json();if(!Array.isArray(data.managers)||!Array.isArray(data.gameweeks))throw new Error('Invalid snapshot');render();$('#updated').textContent=`Last updated: ${new Date(data.updated_at).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})} · Every ${data.refresh_hours} hours`;}catch(error){$('#content').innerHTML=empty('The league snapshot could not be loaded. <button id="retry">Try again</button>');$('#retry').addEventListener('click',load);console.error(error);}}
load();
